In [2]:
import os
os.chdir("C:\\Users\\Adhvaidh\\Desktop\\ML DATASETS\\LINEAR REG")
import numpy as np
import pandas as pd
ds=pd.read_csv("USA_Housing.csv")

In [3]:
ds.tail()

Avg. Area Income  Avg. Area House Age  Avg. Area Number of Rooms  \
4995       60567.94414             7.830362                   6.137356   
4996       78491.27543             6.999135                   6.576763   
4997       63390.68689             7.250591                   4.805081   
4998       68001.33124             5.534388                   7.130144   
4999       65510.58180             5.992305                   6.792336   

      Avg. Area Number of Bedrooms  Area Population        Price  \
4995                          3.46      22837.36103  1060193.786   
4996                          4.02      25616.11549  1482617.729   
4997                          2.13      33266.14549  1030729.583   
4998                          5.44      42625.62016  1198656.872   
4999                          4.07      46501.28380  1298950.480   

                                                Address  
4995                   USNS Williams\nFPO AP 30153-7653  
4996              PSC 9258, Box 8489\nAPO AA 42991-3352  
4997  4215 Tracy Garden Suite 076\nJoshualand, VA 01...  
4998                          USS Wallace\nFPO AE 73316  
4999  37778 George Ridges Apt. 509\nEast Holly, NV 2...

# Checking for % of missing values for each variable

In [4]:
pd.DataFrame(ds).isnull().sum()

Avg. Area Income                0
Avg. Area House Age             0
Avg. Area Number of Rooms       0
Avg. Area Number of Bedrooms    0
Area Population                 0
Price                           0
Address                         0
dtype: int64

In [5]:
## No missing values! 

# Dataframe to array conversion

In [6]:
x=ds.iloc[:,:5].values # All independent varibles to an array x

In [7]:
x

array([[7.95454586e+04, 5.68286132e+00, 7.00918814e+00, 4.09000000e+00,
        2.30868005e+04],
       [7.92486424e+04, 6.00289981e+00, 6.73082102e+00, 3.09000000e+00,
        4.01730722e+04],
       [6.12870672e+04, 5.86588984e+00, 8.51272743e+00, 5.13000000e+00,
        3.68821594e+04],
       ...,
       [6.33906869e+04, 7.25059062e+00, 4.80508098e+00, 2.13000000e+00,
        3.32661455e+04],
       [6.80013312e+04, 5.53438842e+00, 7.13014386e+00, 5.44000000e+00,
        4.26256202e+04],
       [6.55105818e+04, 5.99230531e+00, 6.79233610e+00, 4.07000000e+00,
        4.65012838e+04]])

In [10]:
y=ds.iloc[:,5].values # Dependent variable to an array y

In [11]:
y

array([1059033.558, 1505890.915, 1058987.988, ..., 1030729.583,
       1198656.872, 1298950.48 ])

# Feature scaling

In [12]:
from sklearn.preprocessing import StandardScaler
sc_x=StandardScaler()
x=sc_x.fit_transform(x) # sclaing x(independent variables)

In [13]:
x

array([[ 1.02865969, -0.29692705,  0.02127433,  0.08806222, -1.31759867],
       [ 1.00080775,  0.02590164, -0.25550611, -0.72230146,  0.40399945],
       [-0.68462915, -0.11230283,  1.5162435 ,  0.93084045,  0.07240989],
       ...,
       [-0.48723454,  1.28447022, -2.17026949, -1.50025059, -0.29193658],
       [-0.05459152, -0.44669439,  0.14154061,  1.18205319,  0.65111608],
       [-0.28831272,  0.01521477, -0.19434166,  0.07185495,  1.04162464]])

# Train - Test split

In [14]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(x,y,test_size=0.2, random_state=123)

# Modelling - Linear regression

In [15]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train, y_train) #fitting the model on training data

LinearRegression()

In [16]:
y_pred=regressor.predict(x_test) #Testing it with the test data

In [17]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.9187965773535416

In [18]:
import statsmodels.regression.linear_model as sm

In [19]:
a_train=np.append(arr=x_train, values=np.ones((4000,1)).astype(int),axis=1)
a_train

array([[-0.14641463, -0.34866992, -0.04109073,  0.16099495, -0.22894602,
         1.        ],
       [-0.25421681,  1.34385515,  1.56583501,  0.41220769,  0.36496089,
         1.        ],
       [ 0.3573621 ,  0.06238299, -1.23006839,  0.37979315, -0.35153323,
         1.        ],
       ...,
       [-1.89736968,  0.17595828,  1.25700448,  0.16909859,  1.32907495,
         1.        ],
       [ 0.32337694,  1.10446952, -1.6001682 , -0.46298508,  0.60251417,
         1.        ],
       [ 0.29979728, -0.05643005,  0.42084024,  0.01512949,  0.14816887,
         1.        ]])

In [20]:
regressor_nm=sm.OLS(endog=y_train, exog=a_train).fit()

In [21]:
regressor_nm.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.918
Model:                            OLS   Adj. R-squared:                  0.918
Method:                 Least Squares   F-statistic:                     8915.
Date:                Sun, 22 Nov 2020   Prob (F-statistic):               0.00
Time:                        20:35:01   Log-Likelihood:                -51743.
No. Observations:                4000   AIC:                         1.035e+05
Df Residuals:                    3994   BIC:                         1.035e+05
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1          2.304e+05   1595.933    144.366      0.000    2.27e+05    2.34e+05
x2          1.642e+05   1598.162    102.734      0.000    1.61e+05    1.67e+05
x3            1.2e+05   1787.212     67.169      0.000    1.17e+05    1.24e+05
x4          2115.0963   1785.592      1.185      0.236   -1385.660    5615.853
x5           1.51e+05   1586.078     95.229      0.000    1.48e+05    1.54e+05
const       1.233e+06   1588.386    776.127      0.000    1.23e+06    1.24e+06
==============================================================================
Omnibus:                        5.589   Durbin-Watson:                   2.004
Prob(Omnibus):                  0.061   Jarque-Bera (JB):                4.883
Skew:                           0.008   Prob(JB):                       0.0870
Kurtosis:                       2.830   Cond. No.                         1.65
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""